server:
  port: 8887

#Config Server
spring:
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: id-financial-calculator
          uri: lb://FINANCIAL-CALCULATOR
          predicates:
            - Path=/financial-calculator/**
        - id: id-rental-management
          uri: lb://RENTAL-MANAGEMENT
          predicates:
            - Path=/rental-management/**

# Eureka
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8889/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always