spring:
  application:
    name: rental-management

#Config Server
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000

# Database
  r2dbc:
    url: r2dbc:pool:mysql://autorack.proxy.rlwy.net:51033/railway
    username: root
    password: lgPpyBbpHvzvZmmoZkganhUiyvVggHZa

# Eureka
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8889/eureka

# Calculator Api
api:
  calculator: http://localhost:8082/calculator